### ISSUE TITLE
Height and Width are required, however the documentation does not mention this.

### ISSUE THREAD

**Issue by alex-r89** [Aljullu/react-lazy-load-image-component#10]
Hi,

I have been attempting to use this package, specifically the LazyLoadImage, for a few days in my project. I had it implemented in the same was as the example under the _Using trackWindowScroll HOC to improve performance section_, where an array of images is mapped, however I did not specify a height and width.

With that being said, if you do not explicitly state a height and width - LazyLoadImage will not work. Without height and width, when I fetched 20 images from my API, all of the images were being fetched and loaded to the DOM at once on component render. As soon as I specified height and width, lazy load worked correctly and only images in the view port were being rendered.

I assumed height and width were not required as no where does it state that they are. I define the height and width in my css via a class name on the component, so again did not see the need for a height and width. I also noticed that some examples do not have a height or width passed into the LazyLoadImage, so again, did not think it was required.

This is either an issue with the component, or an issue with the documentation not being clear. Either way, It would be nice to specify this in the documentation :)

**Comment by Aljullu** [comment]
Hi @alex-r89, thanks for bringing this up. The component should work fine without specifying the `height` and `width`. Indeed, I have a working example of that:

https://github.com/Aljullu/react-flickr-gallery

You can see the exact lines here:

https://github.com/Aljullu/react-flickr-gallery/blob/master/src/components/Photo/Photo.jsx#L27

Would you mind sharing the code of your project so I can have a look? I guess the problem is that you are setting a placeholder which doesn't have the same class than the `<img>` element.

By default, the prop `className` is applied to both, the image and the placeholder. But if you specify your own placeholder, you need to set the class on it yourself. Or have a different class but the same size (whatever works better in your case).

Another solution might be creating a wrapper component around `LazyLoadImage` and specify the size on that element.

Hope that helps!

**Comment by ayhid** [comment]
I am having the same issue
without height and width it doe not work.

```javascript
 <LazyLoadImage
        src={`https://image.tmdb.org/t/p/w370_and_h556_bestv2${movie.poster_path}`}       
 placeholderSrc="https://res.cloudinary.com/tiween/image/upload/c_scale,q_10,w_300/v1573680548/film-poster-placeholder.jp2"
        alt={movie.title}
        effect="blur"
        threshold={20}
        wrapperClassName="img-thumbnail"

      />
```
Could you please add some details about it in the docs ?
Thank you for the awesome work
