### ISSUE TITLE
Warning: Expected server HTML to contain a matching <span> in <figure>

### ISSUE THREAD

**Issue by matiasbenedetto** [Aljullu/react-lazy-load-image-component#20]
**Bug description**
When using the lib a warning is printed in the browser console.

**To Reproduce**
When i use this in my NextJs site, the lazy loading works ok but the browser console print a warning.
`<LazyLoadImage
    alt={post.title.rendered}
    src={featuredImage}
/>`

The warning is:
`Warning: Expected server HTML to contain a matching <span> in <figure>`

The problem is also described in this issue: [https://github.com/Aljullu/react-lazy-load-image-component/issues/15](https://github.com/Aljullu/react-lazy-load-image-component/issues/15)

**Expected behavior**
Not show any warning

**Technical details:**
- Server Side Rendering? [Yes]
- Device [Desktop]
- Operating System [GNU/Linux]
- Browser [Firefox and Chrome at least]

**Comment by Aljullu** [comment]
Thanks @matiasbenedetto for opening an issue about that. It looks like it's already two people facing the same issue so there must be something going on.

Unfortunately, I'm still unable to reproduce the issue. It seems to have something to do with `ReactDOM.hydrate()` and `ReactDOM.render()`, but I would need to be able to reproduce it in order to find a fix.

Would you mind sharing your code with me, so I could reproduce the issue? In case you don't want to upload it in public, you could send it to me to my email address (it's in the side bar of my GitHub profile).

**Comment by Aljullu** [comment]
Closing it for now since this issue has been inactive for a while.
